EMPTY_WORDS_PATH = "./emptywords.txt"
# "palabrasvacias.txt"
# "emptywords.txt"
# None

INDEX_FILES_PATH = "../script_1/index_files/"

METADATA_FILE = INDEX_FILES_PATH+"metadata.json"

BIN_VOCABULARY_FILEPATH = INDEX_FILES_PATH+"vocabulary.bin"
BIN_INVERTED_INDEX_FILEPATH = INDEX_FILES_PATH+"inverted_index.bin"
BIN_DOCNAMES_IDS_FILEPATH = INDEX_FILES_PATH+"docnames_ids.bin"
BIN_POSITIONS_FILEPATH = INDEX_FILES_PATH+"positions.bin"

OPERADOR_FRASE = "\""
OPERADOR_CERCA = "CERCA_DE"
OPERADOR_SIGUIENTE = "SIGUIENTE_A"
DISTANCIA_CERCANIA = 3
