INDEX_FILES_PATH = "../script_1/index_files/"

METADATA_FILE = INDEX_FILES_PATH+"metadata.json"

BIN_VOCABULARY_FILEPATH = INDEX_FILES_PATH+"vocabulary.bin"
BIN_INVERTED_INDEX_GAMMA_FILEPATH = INDEX_FILES_PATH+"inverted_index_gamma.bin"
BIN_INVERTED_INDEX_VARIABLE_FILEPATH = INDEX_FILES_PATH+"inverted_index_variable.bin"
BIN_INVERTED_INDEX_FILEPATH = INDEX_FILES_PATH+"inverted_index.bin"

