INDEX_FILES_PATH = "../script_1/output/index_files/"

METADATA_FILE = INDEX_FILES_PATH+"metadata.json"

BIN_VOCABULARY_FILEPATH = INDEX_FILES_PATH+"vocabulary.bin"
BIN_INVERTED_INDEX_FILEPATH = INDEX_FILES_PATH+"inverted_index.bin"
BIN_DOCNAMES_IDS_FILEPATH = INDEX_FILES_PATH+"docnames_ids.bin"
BIN_SKIPS_FILEPATH = INDEX_FILES_PATH+"skips.bin"

AND_SYMBOL = "&"
OR_SYMBOL = "|"
NOT_SYMBOL = "-"

K_SKIPS = 3